name: Deploy to GKE with Istio

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

env:
  DOCKER_HUB_REPO: ashokvsetty/docker-repo
  IMAGE_NAME: calculator

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v4

    - name: 🔐 Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: ☸️ Set up kubectl
      uses: google-github-actions/get-gke-credentials@v2
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}

    - name: 📝 Set image tag in deployment
      run: |
        sed -i "s|\(image: ${{ env.DOCKER_HUB_REPO }}:\).*|\1${{ github.event.inputs.image_tag }}|" k8s/calculator-app.yaml

    - name: 🚀 Deploy app and Istio config
      run: |
        kubectl apply -f k8s/calculator-app.yaml
        kubectl rollout status deployment/calculator-deployment
        kubectl apply -f k8s/calculator-ingress.yaml

    - name: 🌐 Get Istio Ingress IP
      run: |
        echo "Waiting for external IP..."
        for i in {1..20}; do
          IP=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [[ -n "$IP" ]]; then
            echo "Istio Ingress IP: http://$IP"
            break
          fi
          sleep 10
        done
